Expenses/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Expenses.views.home', name='home'),
    # url(r'^Expenses/', include('Expenses.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(
        regex=r'^$',
         view='Expenses.views.view_expenses',
         name='home'
     ),
     url(r'^admin/',
         include(admin.site.urls)
     ),
     url(
         r'^login/$',
         'django.contrib.auth.views.login',
         {'template_name': 'login.html'},
         name="login",

     ),
     url(
         r'^logout',
         'Expenses.views.logout_view',
         name="logout"
     ),
     url(r'^receipts/',
         include('receipts.urls'),
         name='receipts'
     ),
     url(r'^projects/',
         include('projects.urls'),
         name='projects'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT,
                                }),
                            )

projects/urls.py
from django.conf.urls import patterns, url
from projects.views import ProjectListView

urlpatterns = patterns('',
                       url(r'^$',
                           view=ProjectListView.as_view(),
                           name='project_index'
                       ),
                       url(
                           regex=r'^create/$',
                           view='projects.views.add_project',
                           name='project_create'
                       ),
                       url(
                           regex=r'^(?P<slug>[-\w]+)$',
                           view='projects.views.view_project',
                           name='projects_detail'
                           ),
                       url(
                           regex=r'^detail/(?P<pk>\d+)',
                           view='projects.views.participation_detail',
                           name='participation_detail'

                       ),
                        url(
                            regex=r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/delete/$',
                            view='projects.views.participation_remove',
                            name='participation_remove'
                        ),
)

projects/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import ForeignKey
from django.utils.encoding import smart_text
from django_iban.fields import IbanAccountField
from django.template.defaultfilters import slugify


class Address(models.Model):
    first_name = models.CharField(max_length=48)
    family_name = models.CharField(max_length=48)
    company_name = models.CharField(blank=True, max_length=48)
    street = models.CharField(max_length=48)
    number = models.CharField(max_length=5,  blank=True, null=True)
    zip_code = models.CharField(max_length=6)
    city = models.CharField(max_length=50)


class BankAccount(models.Model):
    account_number = IbanAccountField()
    bank_name = models.CharField(max_length=50)
    user_address = ForeignKey(Address)


class Project(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return smart_text(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('projects_detail', (), {'slug' : self.slug})


class ProjectParticipation(models.Model):
    user = models.ForeignKey(User, related_name='participations')
    project = models.ForeignKey(Project)
    pay_date = models.DateField(blank=True, null=True)
    bank_account = models.ForeignKey(BankAccount, blank=True, null=True)

    def is_paid(self):
        return self.pay_date

    def __unicode__(self):
        return u"{0}: {1}".format(self.project.name, self.user)

    class Meta:
        unique_together=("user", "project")

    @models.permalink
    def get_absolute_url(self):
        return ('participation_detail', (), {'pk' : self.id})

projects/forms.py
from django import  forms
from django.forms import HiddenInput
from parsley.decorators import parsleyfy
from projects.models import Project, ProjectParticipation
from receipts.forms import ReceiptForm, ProjectModelChoiceField
from receipts.models import Receipt


@parsleyfy
class ProjectForm(forms.ModelForm):

    class Meta:
        model=Project
        exclude=['slug']


class ParticipationForm(forms.ModelForm):
    class Meta:
        model=ProjectParticipation
        fields= ['user']


class ReceiptParticipationForm(ReceiptForm):
    participation = ProjectModelChoiceField(queryset= ProjectParticipation.objects,
                                            widget=HiddenInput)

projects/views.py
# Create your views here.
from braces.views import StaffuserRequiredMixin
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView
from projects.forms import ProjectForm, ParticipationForm, ReceiptParticipationForm
from projects.models import ProjectParticipation, Project
from receipts.forms import ReceiptForm
from receipts.models import Receipt


@user_passes_test(lambda u: u.is_staff)
def add_project(request):
    """
    View to add a project.
    """
    form=ProjectForm(request.POST or None)
    if form.is_valid():
        project=form.save(commit=False)
        project.save()
        return redirect(project)
    return render_to_response('projects/project_form.html', {'form': form}, context_instance=RequestContext(request))


@user_passes_test(lambda u: u.is_staff)
def view_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    form = ParticipationForm(request.POST or None)
    participations = ProjectParticipation.objects.filter(project=project)
    receipts = Receipt.objects.filter(participation__in=participations)
    users = participations.values_list('user', flat=True).order_by('user')
    form.fields['user'].queryset = form.fields['user'].queryset.exclude(id__in=users)
    if form.is_valid():
        participation = form.save(commit=False)
        participation.project = project
        participation.save()
        return redirect(request.path)
    return render_to_response('projects/project_detail.html', { 'project': project, 'form': form},
                       context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff)
def participation_remove(request, slug, pk):
    if request.POST:
        ProjectParticipation.objects.get(id=pk).delete()
        return HttpResponse(status=200)
    return HttpResponse(status=404)


class ProjectListView(StaffuserRequiredMixin, ListView):
    model = Project


@login_required
def participation_detail(request, pk):
    participation = get_object_or_404(ProjectParticipation, id=pk)
    receipts = Receipt.objects.filter(participation=participation)
    form = ReceiptParticipationForm(request.POST or None,initial={'participation': participation})

    if form.is_valid():
        receipt = form.save(commit=False)
        receipt.participation = participation
        receipt.save()
        return redirect(request.path)
    return render_to_response('projects/participation_detail.html', {'participation' : participation,
                                                                     'receipts' : receipts,
                                                                     'form' : form},
                              context_instance=RequestContext(request))

templates/projects/participation_detail.html
{% extends "Expenses_logged_in.html" %}

{% block page_title %} Home {% endblock %}
{% block content %}
    {{ block.super }}
    <div id="dialog" title="Confirm delete"></div>

    {%  include "receipts/receipts_table.html" with disable_project=True%}


    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" name="submit" value="Add" />
    </form>

{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">
        $(function(){
            $("#dialog").dialog({
                modal: true,
                autoOpen:false
            });
            $("a.delete").click(function(e) {
                e.preventDefault();
                var id = $(this).attr('id');
                var the_url = "{% url 'receipts_delete' 999 %}".replace (999, id);
                $("#dialog").dialog('option', 'buttons', {
                    "Delete": function() {
                        $.ajax({
                            headers : {
                                "X-CSRFToken": $("input[name='csrfmiddlewaretoken']").val()
                            },
                            type: "POST",
                            url: the_url,
                            {#                            data: {'pk': id},#}
                            success: function() {
                                location.reload();
                            }
                        });
                        $(this).dialog("close");
                    },
                    "Cancel": function() {
                        $(this).dialog("close");
                    }
                });
                $("#dialog").dialog("open");
                return false;
            });

        });
    </script>
{%  endblock %}

templates/projects/project_detail.html
{% extends "Expenses_logged_in.html" %}

{% load extra_tags %}

{% block page_title %} Project Details {% endblock %}
{% block content %}
    {{ block.super }}
    <h2>{{ project.name }}</h2>

    <div class="content">
        <p>
            {{ project.description }}
        </p>
    <span>
        Start date: {{ project.start_date }}
    </span>
        {% if project.end_date %}
    <span>
        End date: {{ project.end_date }}
    </span>
        {% endif %}
    </div>

    {% if project.projectparticipation_set.all %}
        <h2>Participates</h2>
        <div id="dialog" title="Confirm delete">Are you sure?</div>
                <table class="participates table table-striped" width=auto>
                    <thead>
                        <tr>
                            <th> User </th>
                            <th>  Sum </th>
                            <th> Paid? </th>
                            <th>  Delete? </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for pp in project.projectparticipation_set.all  %}
                        <tr>
                            <td>{{ pp.user }}</td>
                            <td class="amount"> {{ pp.receipt_set|total_sum }}</td>
                            <td>{{ pp.is_paid }}</td>
                            <td><a id="{{ pp.id }}" href="#" class="delete" >Remove </a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>Total</td>
                            <td class="total"></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
    {% endif %}

    <br />

    <h2>Add User</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" name="submit" value="Add" />
    </form>
{% endblock content %}
{%  block extra_js %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">
        $(function(){
            $("#dialog").dialog({
                modal: true,
                autoOpen:false
            });
            $("a.delete").click(function(e) {
                e.preventDefault();
                var slug = "{{  project.slug }}"
                var id = $(this).attr('id');
                var the_url = "{% url 'participation_remove' 999 888 %}".replace (999, slug).replace(888, id);
                $("#dialog").dialog('option', 'buttons', {
                    "Delete": function() {
                        $.ajax({
                            headers : {
                                "X-CSRFToken": $("input[name='csrfmiddlewaretoken']").val()
                            },
                            type: "POST",
                            url: the_url,
                            data: {'pk': id},
                            success: function() {
                                deleteRow(id);
                                location.reload();
                            }
                        });
                        $(this).dialog("close");
                    },
                    "Cancel": function() {
                        $(this).dialog("close");
                    }
                });
                $("#dialog").dialog("open");
                return false;
            });

        });
    </script>
    <script type="text/javascript">
        $(function()
                {
                    function sum_it(the_class)
                    {
                        var total= 0;

                    }
                }
        )
    </script>
{%  endblock extra_js%}

templates/projects/project_form.html
{% extends "Expenses_logged_in.html" %}

{% block page_title %} Project Details {% endblock %}
{% block content %}
    {{ block.super }}
    <h2>Add new project</h2>
    <form data-validate="parsley" action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" name="add" value="Add" />
    </form>
{% endblock content %}

templates/projects/project_list.html
{% extends "Expenses_logged_in.html" %}
{% block page_title %} Projects {% endblock %}
{% block content %}
{{ block.super }}
    {% for project in object_list %}
    {% if forloop.counter|divisibleby:"5" or forloop.counter == 1 %}
    <div class="row-fluid show-grid">
    {% endif %}
        <div class="span2"><a href="{{  project.get_absolute_url }}">{{ project.name }}</a></div>
    {% if forloop.counter|divisibleby:"4" %}
    </div>
    {% endif %}
    {%  endfor %}
    {% if not object_list.count|divisibleby:"4" %}
    </div>
    {% endif %}
     <div class="row-fluid show-grid">
        <div class="span8"><a href="{% url 'project_create' %}"> Create new Project</a></div>
     </div>
{% endblock content %}